apiVersion: apps/v1
kind: Deployment
metadata:
  name: afsb-dtp-staging-eks-cluster
  namespace: apps
  labels:
    app: afsb-dtp-staging-eks-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: afsb-dtp-staging-eks-cluster
  template:
    metadata:
      labels:
        app: afsb-dtp-staging-eks-cluster
    spec:
      containers:
        - name: afsb-dtp-staging-eks-cluster
          image: 806263047535.dkr.ecr.ap-southeast-1.amazonaws.com/afsb-dtp-staging-repo:latest
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: afsb-dtp-error
  namespace: apps
  labels:
    app: afsb-dtp-error
spec:
  replicas: 1
  selector:
    matchLabels:
      app: afsb-dtp-error
  template:
    metadata:
      labels:
        app: afsb-dtp-error
    spec:
      containers:
        - name: afsb-dtp-error
          image: 806263047535.dkr.ecr.ap-southeast-1.amazonaws.com/afsb-dtp-error-repo:latest  # Replace with your error handling image
          ports:
            - containerPort: 80