apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: apps
spec:
  ingressClassName: nginx
  rules:
    - http:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-ingress-svc
              port:
                number: 80
