apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: app-svc
      port:
        number: 80
  rules:
    - host: test.focuslearningorg.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-svc
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: error-ingress
  namespace: error
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: error-svc
      port:
        number: 80
  rules:
    - host: test.focuslearningorg.com
      http:
        paths:
          - path: /error
            pathType: Prefix
            backend:
              service:
                name: error-svc
                port:
                  number: 80
