apiVersion: v1
kind: Service
metadata:
  annotations:
    ## Name of the ALB
    # alb.ingress.kubernetes.io/group.name: dtp-eks-cluster-ingress
    # alb.ingress.kubernetes.io/load-balancer-name: dtp-eks-cluster-ingress
    # alb.ingress.kubernetes.io/scheme: internet-facing
    # kubernetes.io/ingress.class: alb
  name: app-svc
spec:
  # ingressClassName: alb
  type: NodePort
  selector:
    app: app
  ports:
    - name: svc-port
      port: 80
      targetPort: 80
      nodePort: 32654
      protocol: TCP


