apiVersion: v1
kind: Service
metadata:
  annotations:
    # Name of the ALB
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip        
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external 
    kubernetes.io/ingress.class: "nginx"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  name: app-svc
spec:
  # ingressClassName: alb
  type: ClusterIP
  selector:
    app: app
  ports:
    - name: app-svc
      port: 80
      targetPort: 80
      # nodePort: 30888
      protocol: TCP


