apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  # ingressClassName: alb
  type: ClusterIP
  selector:
    app: app
  ports:
    - name: app-svc
      port: 80
      targetPort: 80
      # nodePort: 30888
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: error-svc
  namespace: error
spec:
  type: ClusterIP
  selector:
    app: app-error
  ports:
    - name: error-svc
      port: 80
      targetPort: 80
      # nodePort: 30888
      protocol: TCP
