apiVersion: v1
kind: Service
metadata:
  annotations:
    ## Name of the ALB
    alb.ingress.kubernetes.io/group.name: dtp-eks-cluster-ingress
    ## The lowest possible priority
    alb.ingress.kubernetes.io/group.order: "100"
    ## Name of the ALB
    alb.ingress.kubernetes.io/load-balancer-name: dtp-eks-cluster-ingress
    ## Must be the same as in `aws_lb.ingress.internal`
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
  name: app-svc
spec:
  type: ClusterIP
  selector:
    name: app
  ports:
    - name: svc-port
      port: 80
      targetPort: 80
      protocol: TCP


