apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-svc
  namespace: apps
  labels:
    app.kubernetes.io/name: nginx-ingress-svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: afsb-dtp-staging-eks-cluster
  ports:
    - name: svc-port
      port: 80
      targetPort: app-port
      protocol: TCP
