apiVersion: v1
kind: Service
metadata:
  annotations:
    ## Name of the ALB
    alb.ingress.kubernetes.io/group.name: ingress-lb
    alb.ingress.kubernetes.io/load-balancer-name: ingress-lb
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
  name: app-svc
spec:
  # ingressClassName: alb
  type: ClusterIP
  selector:
    app: app
  ports:
    - name: svc-port
      port: 80
      targetPort: 80
      protocol: TCP


